[package]
name = "orchard"
version = "0.1.0"
edition = "2024"

[features]
long_json = []

[dependencies]
rumqttc = { version = "0.25.1", features = ["use-native-tls"] }
tokio = "1.52.1"
clap = { version = "4.6.1", features = ["derive", "env"] }
gethostname = "1.1.0"
dotenv = "0.15.0"
orchard_macros = { path = "orchard_macros" }
derive_more = { version = "2.1.1", features = ["from"] }
async-trait = "0.1.89"

thiserror = "2.0.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_with = "3.19.0"
strum = { version = "0.28.0", features = ["derive"] }

volumecontrol = "0.1.4"
system_shutdown = "4.1.0"
sysinfo = "0.39.5"

[target.'cfg(target_os = "linux")'.dependencies]
mpris = "2.0.1"
